apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

commonLabels:
  appStageTag: production

generatorOptions:
  # commonLabels will not be respected by generator
  labels:
    app: overlays-example
    app.kubernetes.io/managed-by: kustomize
    appStageTag: production


patchesStrategicMerge:
- deploymentconfig.yaml
# - service.yaml
