---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: simple-example
    appStageTag: development
  name: simple-example
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentconfig: simple-example
  sessionAffinity: None
  type: ClusterIP
